apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-06-01T14:12:41Z"
  generation: 1
  labels:
    app: firstappdep
  name: firstappdep
  namespace: default
  resourceVersion: "7295"
  uid: 7e53b9ad-3cbc-4b7f-a142-842d3e320357
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: firstappdep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstappdep
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
